version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: "unless-stopped"
    user: root
    # env_file:
    #   - backend/.
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${SA_PASSWORD}
    expose:
      - "${DB_PORT}"
    healthcheck:
        test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "SELECT 1"]
        interval: 10s
        retries: 60
    volumes:
      - db-data:/var/opt/mssql/data
    networks:
      - net

  backend:
    image: xkeiro/el-proyecte-grande:backend
    restart: "unless-stopped"
    build:
      context: backend
      dockerfile: Dockerfile
    expose:
      - "${BACKEND_PORT}"
    links:
        - frontend
    depends_on:
      db:
        condition: service_healthy
    # env_file:
    #   - backend/.env
    environment:
      JWT_TOKEN_KEY: ${JWT_TOKEN_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      DB_SERVER: ${DB_SERVER}
      DB_DATABASE: ${DB_DATABASE}
      DB_ID: ${DB_ID}
      DB_PASSWORD: ${DB_PASSWORD}
      VIRTUAL_HOST: ${DOMAIN}
      VIRTUAL_PORT: ${BACKEND_PORT}
      LETSENCRYPT_HOST: ${DOMAIN}
      VIRTUAL_PATH: /api
    #  VIRTUAL_DEST: /
    volumes:
      - ./backend/UploadedImages:/app/UploadedImages
    networks:
      - net

  frontend:
    image: xkeiro/el-proyecte-grande:frontend
    restart: "unless-stopped"
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - API_URL=${VITE_API_URL}
        - FRONTEND_PORT=${VITE_FRONTEND_PORT}
    # env_file:
    #   - frontend/.env
    expose:
      - "${FRONTEND_PORT}"
    environment:
      VIRTUAL_PORT: ${FRONTEND_PORT}
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      VIRTUAL_PATH: /
    networks:
      - net

volumes:
  db-data:

networks:
  net:
    external: true
